### ISSUE TITLE
MoveGroupCommander.get_current_joint_values() does not work as described

### ISSUE THREAD

**Issue by jim-rothrock** [moveit/moveit_commander#10]
The documentation comment for MoveGroupCommander.get_current_joint_values() states the following:

<pre>
Get the current configuration of the group as a dictionary (these are values published on /joint_states)
</pre>

However, get_current_joint_values() actually returns a list of the group's joint positions (a list of floats). Which is right, the comment, or the behavior?

**Comment by sachinchitta** [comment]
The behavior - the comment has been corrected.
