### ISSUE TITLE
.deb installing to the wrong place?

### ISSUE THREAD

**Issue by diecastzinc** [moveit/moveit_commander#25]
Installing from debs, my moveit_commander_cmdline.py is in /opt/ros/hydro/lib/moveit_commander/, not /opt/ros/hydro/lib/python2.7/dist-packages with the rest of the scripts.

As a result, rosrun moveit_commander moveit_commander_cmdline.py doesn't work.

**Comment by mikeferguson** [comment]
rosrun won't look in dist-packages, thats for things you want to find through the python path -- it looks in /opt/ros/<distro>/lib/<pkg_name> -- so the location you mention is the correct one -- what is the error that you get when trying to rosrun -- and what does your ros path look like ("echo $ROS_PACKAGE_PATH")

**Comment by diecastzinc** [comment]
Hrm. My ROS_PACKAGE_PATH is /home/dcz/catkin_ws/src:/opt/ros/hydro/share:/opt/ros/hydro/stacks

The error is: [rosrun] Couldn't find executable named moveit_commander_cmdline.py below /opt/ros/hydro/share/moveit_commander

Is it just a matter of adding /opt/ros/hydro/lib to ROS_PACKAGE_PATH? If so, I'm pretty sure that's not part of the installation instructions, should it be?

**Comment by mikeferguson** [comment]
Ok, so lib won't be in the path -- but the fact that share is in the path tells me that your paths are probably set up properly. What is the output of "catkin_find moveit_commander" (which is what happens under the hood, on my system it finds both lib and share folders)? For that matter, what version is catkin?

**Comment by diecastzinc** [comment]
Agh! Problem solved with catkin_find:

/home/dcz/catkin_ws/devel/share/moveit_commander
/opt/ros/hydro/lib/moveit_commander
/opt/ros/hydro/share/moveit_commander

I d/led from source a while back, guess it was looking for moveit_commander_cmdline.py in ~/catkin_ws/src/moveit_commander but when I deleted the folder from src, it kept leftovers in devel. It'd be nice if catkin cleaned up after itself... :)

Thanks so much for your help.
