### ISSUE TITLE
Python module locations on Jade

### ISSUE THREAD

**Issue by timburgess** [moveit/moveit_commander#33]
I've complied moveit on Jade on vivid 15.04, which has installed <code>moveit_commander</code> into <code>/usr/local/lib/python2.7/dist-packages</code> which is where I would expect it. However all the other built modules remain in <code>/moveit/devel/lib/python2.7/dist-packages</code>. Should the install put them into the same dir as moveit_commander (as it has dependencies on moveit_ros_planning_interface) or is it more usual to add the /devel path to your python sys.path. I was kinda expecting that as built modules they would go into the same dir as moveit_commander..

**Comment by 130s** [comment]
> I've complied moveit on Jade on vivid 15.04, which has installed moveit_commander into `/usr/local/lib/python2.7/dist-packages` which is where I would expect it. 

Compiling by ROS standard tools (e.g. catkin) would probably never put the binaries into protected directory as `/usr` etc AFAIK. How did you compile? 
I recommend you go through again [ROS tutorial about building](http://wiki.ros.org/ROS/Tutorials/BuildingPackages).

If you still have an issue please reopen.
