### ISSUE TITLE
Add methods to PlanningSceneInterface already present on C++ version

### ISSUE THREAD

**Issue by corot** [moveit/moveit_commander#39]
The missing methods are:
- get_known_object_names
- get_known_object_names_in_roi

And I also added the new ones added on PR https://github.com/ros-planning/moveit_ros/pull/641
- get_object_poses
- get_objects
- get_attached_objects

Still missing are:
- addCollisionObjects
- removeCollisionObjects

I'll try to implement them when I get some extra time

**Comment by v4hn** [comment]
long merged.
