### ISSUE TITLE
can't import moveit_commander 

### ISSUE THREAD

**Issue by anthonio4990** [moveit/moveit_commander#53]
hi, 

im using ubuntu 14.04 on ROS-indigo. i tried to run this code:

```
> #!/usr/bin/env python
> import sys
> import copy
> import rospy
> import moveit_commander
> import moveit_msgs.msg
> 
```

but then i got the following error:

```
> anthonio@PC190:~/kuka_bot$ rosrun agilus testing.py
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
>   what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
> Aborted (core dumped)
> 
```

can someone please help me?

**Comment by v4hn** [comment]
Hey anthonio4990,

we merged this repo into https://github.com/ros-planning/moveit just today.
Could you file the issue over there please?

In this context please test whether this also happens with the latest git checkout
from that repo and also add the information whether you use the osrf-packaged
ros-indigo-moveit-\* packages or source build.

Thanks in advance!

Closing.
